CREATE TABLE user (
    id INTEGER PRIMARY KEY NOT NULL,
    email TEXT UNIQUE NULL
);
CREATE TABLE session (
    token TEXT PRIMARY KEY NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user" (id)
);
